import Head from 'next/head'
import Header from '@/components/Header';
import Footer from '@/components/Footer';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <h1 className='bg-red-300'>Hello World!!</h1>
      <Footer />
    </div>
  )
}
